### ISSUE TITLE
DevExpress v14.2.6 và EntityFramework 6.1.3

### ISSUE THREAD

**Issue by htran282** [chungminhtu/NTP_MVC#1]
Các bạn có thể thống nhất dùng các version này trong webconfig được không. Mình lấy code về lại phải install bản 14.2.3 (cũ hơn) và install EntityFramework.

**Comment by chungminhtu** [comment]
OK anh. em sẽ update lên ver mới nhất cho phù hợp với team của a. Hiện tại code đã merge cả 2 hệ thống và đưa lên server test
